[package]
name = "frontend2"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew"}
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.22"
failure = "0.1.1"
